export interface LibraryItem {
  id: string;
  name: string;
  nameEn: string;
  category: "personaggio" | "luogo" | "tema";
  cantica: "Inferno" | "Purgatorio" | "Paradiso" | "Tutte";
  canto: string;
  cantoEn: string;
  symbol: string;
  quote: string;
  quoteTranslation: string;
  summary: string;
  summaryEn: string;
  explanation: string;
  explanationEn: string;
  tags: string[];
}

export const libraryItems: LibraryItem[] = [
  {
    id: "dante",
    name: "Dante Alighieri",
    nameEn: "Dante Alighieri",
    category: "personaggio",
    cantica: "Tutte",
    canto: "Tutta l'opera",
    cantoEn: "Entire Work",
    symbol: "✍️",
    quote: "Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura...",
    quoteTranslation: "Midway upon the journey of our life I found myself within a forest dark...",
    summary: "Il protagonista (Viator) e autore dell'opera. Rappresenta l'uomo smarrito che ripercorre il sentiero del peccato per riscoprire la Grazia e la salvezza.",
    summaryEn: "The protagonist (Viator) and author of the work. He represents lost humanity tracing the path of sin to rediscover Grace and salvation.",
    explanation: "Dante ha un doppio ruolo fondamentale: l'attore (quello che vive il viaggio e si spaventa o sviene) e il narratore (quello che scrive l'opera ricordando l'evento). Il suo viaggio simboleggia la crescita interiore e il riscatto spirituale di tutta l'umanità.",
    explanationEn: "Dante serves a dual role: the character (who experiences the journey, faints from pity, or fears) and the narrator (who writes down the memories). His journey symbolizes inner growth and the redemption of all mankind.",
    tags: ["Protagonista", "Esilio", "Poesia", "Umanità"]
  },
  {
    id: "virgilio",
    name: "Virgilio",
    nameEn: "Virgil",
    category: "personaggio",
    cantica: "Inferno",
    canto: "Inferno I - Purgatorio XXX",
    cantoEn: "Inferno I - Purgatorio XXX",
    symbol: "🧙",
    quote: "Non uom, uomo già fui, e li parenti miei furon lombardi...",
    quoteTranslation: "Not man; man once I was, and both my parents were Lombards...",
    summary: "Grande poeta latino autore dell'Eneide. Invia da Beatrice nel Limbo, guida Dante attraverso l'Inferno e il Purgatorio. Rappresenta la Ragione umana.",
    summaryEn: "Great Latin poet, author of the Aeneid. Sent by Beatrice, he guides Dante through Inferno and Purgatorio. He represents human Reason.",
    explanation: "Virgilio incarna la filosofia e la conoscenza razionale degli antichi. Aiuta Dante a vincere la paura della selva ma non può entrare in Paradiso poiché nacque prima di Cristo e non ha la fede cristiana. Lascerà il posto a Beatrice sulla vetta del Purgatorio.",
    explanationEn: "Virgil embodies classical philosophy and rational knowledge. He helps Dante conquer his fear of the forest, but cannot enter Paradise because he was born before Christ and lacks faith. He transitions guidance to Beatrice at Purgatory's peak.",
    tags: ["Saggezza", "Guida", "Ragione", "Filosofia"]
  },
  {
    id: "beatrice",
    name: "Beatrice Portinari",
    nameEn: "Beatrice Portinari",
    category: "personaggio",
    cantica: "Paradiso",
    canto: "Purgatorio XXX - Paradiso XXXIII",
    cantoEn: "Purgatory XXX - Paradiso XXXIII",
    symbol: "🕊️",
    quote: "Guardami ben: ben son, ben son Beatrice!",
    quoteTranslation: "Look on me well: yes, I am Beatrice indeed!",
    summary: "La donna amata da Dante e la sua musa salvifica. Scende nel Limbo per soccorrerlo e lo guida nei cieli del Paradiso. Rappresenta la Teologia e la Carità Divina.",
    summaryEn: "Dante's beloved woman and saving muse. She descends to Limbo to aid him and guides him through Paradise. Representing Faith and Divine Love.",
    explanation: "Oltre ad essere un personaggio storico (la fiorentina Beatrice Portinari), nella Commedia assume una valenza puramente simbolica: la Grazia Divina, la Teologia e lo scudo protettivo che difende l'intelletto umano conducendolo alla contemplazione di Dio.",
    explanationEn: "Besides being a real historic figure from Florence, in the Comedy she takes on a purely allegorical value: Divine Grace, Theology, and the spiritual shield leading human intellect to contemplate God.",
    tags: ["Amore", "Fede", "Guida", "Paradiso"]
  },
  {
    id: "caronte",
    name: "Caronte",
    nameEn: "Charon",
    category: "personaggio",
    cantica: "Inferno",
    canto: "Inferno IIIvv. 82-111",
    cantoEn: "Inferno III vv. 82-111",
    symbol: "🚣",
    quote: "Guai a voi, anime prave! Non isperate mai veder lo cielo...",
    quoteTranslation: "Woe unto you, ye souls depraved! Hope nevermore to look upon the heavens...",
    summary: "Il nocchiero infernale che trasporta le anime dannate attraverso il fiume Acheronte. Ha occhi circondati di fiamme e minaccia i peccatori.",
    summaryEn: "The demonic ferryman who transports the souls of the damned across the Acheron river. He has eyes ringed with fire and threatens sinners.",
    explanation: "Dante adatta questa figura della mitologia greca e romana (Eneide) trasformandola in un demonio spietato. Caronte protesta quando vede Dante vivo, ma Virgilio lo zittisce dicendo che il viaggio è voluto da Dio ('Vuolsi così colà dove si puote...').",
    explanationEn: "Dante adapts this classic figure from Greek and Roman mythology (Virgil's Aeneid) transforming him into a ruthless demon. Charon protests seeing a living soul, but Virgil silences him, asserting that the journey is willed from above.",
    tags: ["Mostro", "Inferno", "Mitologia", "Acheronte"]
  },
  {
    id: "minosse",
    name: "Minosse",
    nameEn: "Minos",
    category: "personaggio",
    cantica: "Inferno",
    canto: "Inferno V vv. 1-24",
    cantoEn: "Inferno V vv. 1-24",
    symbol: "⚖️",
    quote: "Stavi Minòs terribilmente, e ringhia: essamina le colpe ne l'entrata...",
    quoteTranslation: "There Minos stands, horrific, and he snarls: examines the transgressions at the entry...",
    summary: "Il giudice dell'Inferno placed all'ingresso del secondo cerchio. Ringhia selvaggiamente e giudica i peccati avvolgendo la sua lunga coda.",
    summaryEn: "The ancient judge of Hell sitting at the entrance of the second circle. He snarls and judges sins by wrapping his tail.",
    explanation: "Ogni anima confessa i suoi peccati davanti a lui. Minosse avvolge la coda intorno al proprio corpo: il numero di giri indica a quale cerchio dell'ampio imbuto infernale l'anima è destinata a cadere per sempre.",
    explanationEn: "Every soul confesses its sins before him. Minos wraps his tail around his body: the number of coils designates the exact circle of Hell where the soul is condemned to fall eternally.",
    tags: ["Giudizio", "Mostro", "Inferno", "Coda"]
  },
  {
    id: "paolo-francesca",
    name: "Paolo e Francesca",
    nameEn: "Paolo and Francesca",
    category: "personaggio",
    cantica: "Inferno",
    canto: "Inferno V vv. 73-142",
    cantoEn: "Inferno V vv. 73-142",
    symbol: "👩‍❤️‍👨",
    quote: "Amor, ch'a nullo amato amar perdona, mi prese del costui piacer sì forte...",
    quoteTranslation: "Love, that exempts no one beloved from loving, seized me with pleasure in this man so strongly...",
    summary: "Due anime del cerchio dei lussuriosi, punite in una bufera incessante. Francesca racconta a Dante il loro amore tragico nato leggendo la storia di Lancillotto e Ginevra.",
    summaryEn: "Two souls in the circle of the lustful, punished by an unceasing storm. Francesca tells Dante of their tragic adultery born while reading Lancelot and Guinevere.",
    explanation: "Una delle storie più toccanti della Commedia. Dante mostra forte empatia verso di loro fino a svenire alla fine del canto. Il racconto illustra il pericolo della letteratura erotica che travolge la ragione morale conducendo al peccato.",
    explanationEn: "One of the most touching stories in the Comedy. Dante feels deep empathy, fainting from grief at the canto's close. The narrative underscores the danger of courtly passion which overcomes moral reason.",
    tags: ["Amore", "Passione", "Tragedia", "Lussuria"]
  },
  {
    id: "farinata",
    name: "Farinata degli Uberti",
    nameEn: "Farinata degli Uberti",
    category: "personaggio",
    cantica: "Inferno",
    canto: "Inferno X vv. 22-120",
    cantoEn: "Inferno X vv. 22-120",
    symbol: "🔥",
    quote: "La tua loquela ti fa manifesto di quella nobil patria natio...",
    quoteTranslation: "Thy noble language makes thee manifest of that magnificent fatherland native...",
    summary: "Orgoglioso leader politico della fazione dei Ghibellini a Firenze. Si solleva fiero dalla sua tomba infuocata degli eretici e dialoga con Dante d'esilio.",
    summaryEn: "Proud political leader of the Ghibellines in Florence. He stands tall from his burning tomb of the heretics and discusses exile with Dante.",
    explanation: "Farinata appare maestoso: 'come avesse l'inferno in gran dispitto' (mostrando disprezzo verso l'inferno). Pur essendo tra i condannati, conserva la sua fiera indole aristocratica. Predice a Dante la fatica e lo scontento dell'imminente esilio politico.",
    explanationEn: "Farinata appears majestic, holding Hell in great disdain ('come avesse l'inferno in gran dispitto'). He maintains his proud aristocratic temper, foretelling Dante's bitter future exile.",
    tags: ["Politica", "Orgoglio", "Eretici", "Firenze"]
  },
  {
    id: "ulisse",
    name: "Ulisse",
    nameEn: "Ulysses",
    category: "personaggio",
    cantica: "Inferno",
    canto: "Inferno XXVI vv. 55-142",
    cantoEn: "Inferno XXVI vv. 55-142",
    symbol: "⛵",
    quote: "Fatti non foste a viver come bruti, ma per seguir virtute e canoscenza...",
    quoteTranslation: "Ye were not made to live like unto brutes, but for pursuit of virtue and of knowledge...",
    summary: "L'eroe greco del cavallo di Troia, imprigionato in una doppia lingua di fuoco con Diomede. Racconta del suo ultimo viaggio oltre i limiti del mondo.",
    summaryEn: "The Greek hero of Troy, locked inside a split flame with Diomedes. He narrates his final journey past the pillars of Hercules and his ship's wreck.",
    explanation: "Ulisse rappresenta il desiderio umano della conoscenza. Tuttavia, il suo viaggio è definito un 'folle volo' perché intraprendeva la ricerca di misteri divini affidandosi unicamente all'intelletto e sfidando i limiti imposti agli uomini, senza la Grazia salvifica.",
    explanationEn: "Ulysses embodies the deep human urge for curiosity. However, his travel is deemed a 'mad flight' because he pushed past physical limits relying solely on reason, without faith or divine humility.",
    tags: ["Viaggio", "Conoscenza", "Ingegno", "Folle"]
  },
  {
    id: "ugolino",
    name: "Conte Ugolino",
    nameEn: "Count Ugolino",
    category: "personaggio",
    cantica: "Inferno",
    canto: "Inferno XXXII - XXXIII",
    cantoEn: "Inferno XXXII - XXXIII",
    symbol: "💀",
    quote: "La bocca sollevò dal fiero pasto quel peccator, forbendola a' capelli...",
    quoteTranslation: "His mouth uplifted from the fierce repast that sinner, wiping it upon the hair...",
    summary: "Traditore della patria imprigionato nei ghiacci del Cocito. Morde il cranio dell'Arcivescovo Ruggieri, che lo fece affamare vivi insieme ai suoi figli.",
    summaryEn: "A traitor confined in the ice of Cocytus. He gnaws the skull of Archbishop Ruggieri, who locked him to starve inside a tower with his innocent sons.",
    explanation: "L'ultimo grande dramma dell'Inferno. Ugolino narra la terribile prigionia nella torre di Pisa e l'agonia dei figli che lo supplicavano di cibarsi del loro corpo prima di spirare, dando vita a un grido di dolore cupo e feroce.",
    explanationEn: "The final great drama of Inferno. Ugolino relates lock-up in the Pisan tower and the starvation of his boys, offering a dark and grim cry against human cruelty.",
    tags: ["Vendetta", "Tradimento", "Ghiaccio", "Tragedia"]
  },
  {
    id: "selva",
    name: "La Selva Oscura",
    nameEn: "The Dark Forest",
    category: "luogo",
    cantica: "Inferno",
    canto: "Inferno I",
    cantoEn: "Inferno I",
    symbol: "🌳",
    quote: "...mi ritrovai per una selva oscura, ché la diritta via era smarrita.",
    quoteTranslation: "...I found myself within a forest dark, for the straightforward pathway had been lost.",
    summary: "La spaventosa, fitta foresta buia in cui si apre la Commedia. Simboleggia lo smarrimento morale, l'errore e il peccato dell'uomo.",
    summaryEn: "The terrifying, dense dark woods in which the Comedy begins. It symbolizes moral confusion, error, and human sinfulness.",
    explanation: "Rappresenta l'inizio spirituale della purificazione. Prima di poter vedere la luce della verità e l'armonia delle stelle, l'essere umano deve sprofondare nella consapevolezza dei propri errori, simboleggiata dal bosco aggrovigliato.",
    explanationEn: "It represents the psychological beginning of self-recovery. Before beholding light and stars, a human must cross their own darker path of mistakes, represented by the web of trees.",
    tags: ["Smarrito", "Inizio", "Bosco", "Simbolo"]
  },
  {
    id: "lucifero",
    name: "Lucifero",
    nameEn: "Lucifer / Satan",
    category: "personaggio",
    cantica: "Inferno",
    canto: "Inferno XXXIV vv. 28-139",
    cantoEn: "Inferno XXXIV vv. 28-139",
    symbol: "👹",
    quote: "S'el fu sì bel com'elli è ora brutto, e contra 'l suo fattore alzò le ciglia...",
    quoteTranslation: "If he was once as fair as he is hideous now, and raised his brow against his Maker...",
    summary: "L'angelo ribelle precipitato da Dio al centro esatto della Terra. Gigantesco mostro con tre teste incastrato nel ghiaccio di Cocito.",
    summaryEn: "The rebel archangel cast out by God to the center of Earth. A massive, three-skinned monster frozen inside Cocytus' ice.",
    explanation: "Lucifero batte sei ali pazzesche producendo un vento gelido che congela l'abisso. Nelle sue tre fauci mastica i peggiori traditori della storia: Giuda (che tradì Gesù, fondatore della Chiesa) e Bruto e Cassio (che tradirono Cesare, fondatore dell'Impero).",
    explanationEn: "Lucifer flaps six gigantic bat wings, creating the freezing wind that hardens the lake. In his three mouths he chews history's worst traitors: Judas, Brutus, and Cassius.",
    tags: ["Mostro", "Traditori", "Ghiaccio", "Basso"]
  },
  {
    id: "catone",
    name: "Catone l'Uticense",
    nameEn: "Cato of Utica",
    category: "personaggio",
    cantica: "Purgatorio",
    canto: "Purgatorio I",
    cantoEn: "Purgatorio I",
    symbol: "🏔️",
    quote: "Libertà va cercando, ch'è sì cara, come sa chi per lei vita rifiuta...",
    quoteTranslation: "He goes in search of liberty, which is so dear, as he knows who for it life rejects...",
    summary: "Il custode pagano dell'Antipurgatorio. Difensore integerrimo della libertà morale, scelse il suicidio a Utica pur di non vivere sotto Cesare.",
    summaryEn: "The pagan guardian of Purgatory. An upright defender of moral liberty, he preferred suicide at Utica over servitude under Julius Caesar.",
    explanation: "Nonostante fosse pagano e suicida, Dante lo pone a custodia del monte della purificazione. Questo perché la libertà politica e morale da lui ricercata è intesa come la stessa libertà dal peccato che le anime cercano nel Purgatorio.",
    explanationEn: "Despite being pagan and taking his life, Dante designates him to guard Purgatorio. This is because Cato's pursuit of freedom matches the liberation from sin that souls climb to find.",
    tags: ["Custode", "Libertà", "Purgatorio", "Fermezza"]
  },
  {
    id: "pia-tolomei",
    name: "Pia de' Tolomei",
    nameEn: "Pia de' Tolomei",
    category: "personaggio",
    cantica: "Purgatorio",
    canto: "Purgatorio V vv. 130-136",
    cantoEn: "Purgatorio V vv. 130-136",
    symbol: "💍",
    quote: "Deh, quando tu sarai tornato al mondo... ricorditi di me, che son la Pia...",
    quoteTranslation: "Ah, when thou art returned unto the world... remember me, who am the Pia...",
    summary: "Nobile donna senese uccisa segretamente dal marito in Maremma. Incontra Dante tra chi morì violentemente, sussurrandogli parole dolci.",
    summaryEn: "Noblewoman from Siena secretly killed by her husband in the Maremma. She meets Dante among those who died by violence, asking for a prayer.",
    explanation: "Una figura iconica e delicata. Esprime gentilezza chiedendo a Dante di pregare per lei solo dopo essersi riposato dal lungo viaggio. Rappresenta la compassione e la fragilità delle vittime di abusi familiari.",
    explanationEn: "A delicate, hauntingly kind soul. She asks Dante to pray for her only after he has rested from his tiring travel. She represents victims of secret domestic abuse.",
    tags: ["Gentilezza", "Vittima", "Maremma", "Spiriti"]
  },
  {
    id: "piccarda",
    name: "Piccarda Donati",
    nameEn: "Piccarda Donati",
    category: "personaggio",
    cantica: "Paradiso",
    canto: "Paradiso III vv. 34-120",
    cantoEn: "Paradiso III vv. 34-120",
    symbol: "🌙",
    quote: "Frate, la nostra volontà quieta virtù di carità, che fa volerne sol quel ch'avemo...",
    quoteTranslation: "Brother, our will is quieted by virtue of charity, which makes us wish only for what we have...",
    summary: "Giovane monaca fiorentina rapita dal convento dai fratelli per sposarsi a forza. Risiede nel Cielo della Luna con chi non compì i voti sacri.",
    summaryEn: "A young nun from Florence abducted from her convent by her brothers to marry by force. She resides in the Heaven of the Moon with those who broke vows.",
    explanation: "Piccarda spiega a Dante che nel Paradiso non vi è invidia per chi è più vicino a Dio: la loro felicità consiste precisamente nel conformarsi pienamente alla volontà divina ('e 'n la sua volontade è nostra pace').",
    explanationEn: "Piccarda explains that there's no envy in Paradise: their bliss resides in perfectly agreeing with active divine will ('and in His will is our true peace').",
    tags: ["Pace", "Monaca", "Luna", "Volontà"]
  },
  {
    id: "contrappasso",
    name: "La Teoria del Contrappasso",
    nameEn: "The Law of Retribution",
    category: "tema",
    cantica: "Tutte",
    canto: "Teoria generale",
    cantoEn: "General Concept",
    symbol: "⚖️",
    quote: "Così s'osserva in me lo contrappasso.",
    quoteTranslation: "Thus is observed in me the counterpass.",
    summary: "Il principio metafisico che regola le punizioni nell'Aldilà, legando la pena terrena al peccato commesso per contrasto o somiglianza.",
    summaryEn: "The principal law governing punishments in the afterlife, matching a sinner's penalty to their earthly vice by analogy or contrast.",
    explanation: "Dal latino 'contra-patiar' (soffrire il contrario). Ad esempio: i lussuriosi travolti dall'istinto romantico sono scaraventati da una bufera di vento; gli indovini che vollero guardare troppo avanti nel futuro hanno ora la testa girata all'indietro.",
    explanationEn: "Coined from Latin 'contra-patiar'. For example: the lustful, who couldn't control their passion, are blown by a relentless storm; fortune-tellers, who tried to see forward, have their heads twisted backward.",
    tags: ["Legge", "Giustizia", "Simbolo", "Dottrina"]
  },
  {
    id: "numeri",
    name: "La Simbologia dei Numeri",
    nameEn: "The Symbology of Numbers",
    category: "tema",
    cantica: "Tutte",
    canto: "Struttura generale",
    cantoEn: "General Structure",
    symbol: "🔢",
    quote: "Tre donne benedette curan de te ne la corte del cielo...",
    quoteTranslation: "Three blessed ladies look out for you in the court of heaven...",
    summary: "L'uso ricorrente di numeri carichi di significati allegorici medievali (in particolare il 3, il 9 e il 10) in tutta la struttura poetica.",
    summaryEn: "The recurrent usage of architectural numbers full of medieval allegorical meaning (specifically 3, 9, and 10) in the structure.",
    explanation: "Il numero 3 simboleggia la Trinità: 3 Cantiche, 33 Canti ciascuna (+1 di intro), rima incatenata (terza rima), 3 fiere, 3 guide, 3 facce di Lucifero. Il numero 10 e il suo quadrato 100 rappresentano la perfezione assoluta.",
    explanationEn: "The number 3 embodies the Holy Trinity: 3 parts, 33 cantos each (+1 introduction), 3 guides, 3 wild beasts, 3 faces of Lucifer. The number 10 and its square 100 represent absolute cosmic perfection.",
    tags: ["Matematica", "Trinità", "Struttura", "Dottrina"]
  }
];
